updating
style
	^'html {height:100%; overflow:hidden}
	body {
		overflow:hidden;
		height:100%;
		margin:0;
		padding:0;
		font-size:11px;
		font-family:Verdana}
 	h1 {color:#ff7200;background:#ddd;margin:0;padding:4px;padding-bottom:0px}
	.ui-layout-pane { /* all panes */ 
		background: #FFF; 
		border: 1px solid #BBB; 
		padding: 1px; 
		overflow: auto;
	} 
 	.ui-layout-pane-center {padding:4px;padding-left:10px}
	.ui-layout-pane-north {padding:0px;border-bottom:0px}
	.ui-layout-resizer {   
		background: #DDD; 
	}

 
	.ui-layout-toggler {  
		background: #AAA; 
	} 
	.ui-layout-toggler .content {
	   font-size: 12px; /* IMPORTANT: default = 1px */
	   font-weight: bold;
	   text-align: center}
	.ui-layout-toggler-north .content {   
		 font-size: 7px;
	} 
.ui-accordion .ui-accordion-content {padding-top:0px;padding-bottom:4px !important;}

 '