updating
style
	^'html {height:100%; overflow:hidden}
	body {
		overflow:hidden;
		height:100%;
		margin:0;
		padding:0}
 
	.ui-layout-pane { /* all panes */ 
		background: #FFF; 
		border: 1px solid #BBB; 
		padding: 10px; 
		overflow: auto;
	} 
 
	.ui-layout-resizer {   
		background: #DDD; 
	} 
 
	.ui-layout-toggler {  
		background: #AAA; 
	} 
	.ui-layout-toggler .content {
	   font-size: 12px; /* IMPORTANT: default = 1px */
	   font-weight: bold;
	   text-align: center;
}

 '