private
demoCss
"borrowed from demo page of hoverintent"
^'		/* styles for the demo examples -- NOT REQUIRED for hoverIntent to work, just for demo purposes */
		li { padding-bottom: 0; }
		ul.demo {display:block; width:100%; height:75px; padding:0; margin:0; background:#9cc; list-style-type:none;}
		ul.demo li {background:#fcc; display:block; width:25%; height:50px; padding:0; margin:0; float: left; position:relative; overflow:hidden; cursor:default;  font-size:0.9em; line-height:1.1em;}
		ul.demo li.p2 {background:#ffc;}
		ul.demo li.p3 {background:#cfc;}
		ul.demo li.p4 {background:#ccf;}
		ul.demo li span { display:block; margin:4px; background:#eef; cursor:default;}'