*jqwidgetbox-fullcalendar-core
timeZonesHtoT
	^ {(self offset: 480 minutes name: 'Hotel Time Zone' abbreviation: 'H').
	(self offset: -180 minutes name: 'Heure Avancée de l''Atlantique' abbreviation: 'HAA').
	(self offset: -180 minutes name: 'Heure Avancée de l''Atlantique' abbreviation: 'HAA').
	(self offset: -300 minutes name: 'Heure Avancée du Centre' abbreviation: 'HAC').
	(self offset: -540 minutes name: 'Hawaii-Aleutian Daylight Time' abbreviation: 'HADT').
	(self offset: -240 minutes name: 'Heure Avancée de l''Est' abbreviation: 'HAE').
	(self offset: -240 minutes name: 'Heure Avancée de l''Est' abbreviation: 'HAE').
	(self offset: -420 minutes name: 'Heure Avancée du Pacifique' abbreviation: 'HAP').
	(self offset: -360 minutes name: 'Heure Avancée des Rocheuses' abbreviation: 'HAR').
	(self offset: -600 minutes name: 'Hawaii-Aleutian Standard Time' abbreviation: 'HAST').
	(self offset: -150 minutes name: 'Heure Avancée de Terre-Neuve' abbreviation: 'HAT').
	(self offset: -480 minutes name: 'Heure Avancée du Yukon' abbreviation: 'HAY').
	(self offset: 480 minutes name: 'Hong Kong Time' abbreviation: 'HKT').
	(self offset: -270 minutes name: 'Hora Legal de Venezuela' abbreviation: 'HLV').
	(self offset: -240 minutes name: 'Heure Normale de l''Atlantique' abbreviation: 'HNA').
	(self offset: -240 minutes name: 'Heure Normale de l''Atlantique' abbreviation: 'HNA').
	(self offset: -240 minutes name: 'Heure Normale de l''Atlantique' abbreviation: 'HNA').
	(self offset: -360 minutes name: 'Heure Normale du Centre' abbreviation: 'HNC').
	(self offset: -360 minutes name: 'Heure Normale du Centre' abbreviation: 'HNC').
	(self offset: -300 minutes name: 'Heure Normale de l''Est' abbreviation: 'HNE').
	(self offset: -300 minutes name: 'Heure Normale de l''Est' abbreviation: 'HNE').
	(self offset: -300 minutes name: 'Heure Normale de l''Est' abbreviation: 'HNE').
	(self offset: -480 minutes name: 'Heure Normale du Pacifique' abbreviation: 'HNP').
	(self offset: -420 minutes name: 'Heure Normale des Rocheuses' abbreviation: 'HNR').
	(self offset: -210 minutes name: 'Heure Normale de Terre-Neuve' abbreviation: 'HNT').
	(self offset: -540 minutes name: 'Heure Normale du Yukon' abbreviation: 'HNY').
	(self offset: 420 minutes name: 'Hovd Time' abbreviation: 'HOVT').
	(self offset: 540 minutes name: 'India Time Zone' abbreviation: 'I').
	(self offset: 420 minutes name: 'Indochina Time' abbreviation: 'ICT').
	(self offset: 180 minutes name: 'Israel Daylight Time' abbreviation: 'IDT').
	(self offset: 360 minutes name: 'Indian Chagos Time' abbreviation: 'IOT').
	(self offset: 270 minutes name: 'Iran Daylight Time' abbreviation: 'IRDT').
	(self offset: 540 minutes name: 'Irkutsk Summer Time' abbreviation: 'IRKST').
	(self offset: 480 minutes name: 'Irkutsk Time' abbreviation: 'IRKT').
	(self offset: 210 minutes name: 'Iran Standard Time' abbreviation: 'IRST').
	(self offset: 120 minutes name: 'Israel Standard Time' abbreviation: 'IST').
	(self offset: 330 minutes name: 'India Standard Time' abbreviation: 'IST').
	(self offset: 60 minutes name: 'Irish Standard Time' abbreviation: 'IST').
	(self offset: 540 minutes name: 'Japan Standard Time' abbreviation: 'JST').
	(self offset: 600 minutes name: 'Kilo Time Zone' abbreviation: 'K').
	(self offset: 360 minutes name: 'Kyrgyzstan Time' abbreviation: 'KGT').
	(self offset: 480 minutes name: 'Krasnoyarsk Summer Time' abbreviation: 'KRAST').
	(self offset: 420 minutes name: 'Krasnoyarsk Time' abbreviation: 'KRAT').
	(self offset: 540 minutes name: 'Korea Standard Time' abbreviation: 'KST').
	(self offset: 240 minutes name: 'Kuybyshev Time' abbreviation: 'KUYT').
	(self offset: 660 minutes name: 'Lima Time Zone' abbreviation: 'L').
	(self offset: 660 minutes name: 'Lord Howe Daylight Time' abbreviation: 'LHDT').
	(self offset: 630 minutes name: 'Lord Howe Standard Time' abbreviation: 'LHST').
	(self offset: 840 minutes name: 'Line Islands Time' abbreviation: 'LINT').
	(self offset: 720 minutes name: 'Mike Time Zone' abbreviation: 'M').
	(self offset: 720 minutes name: 'Magadan Summer Time' abbreviation: 'MAGST').
	(self offset: 660 minutes name: 'Magadan Time' abbreviation: 'MAGT').
	(self offset: -570 minutes name: 'Marquesas Time' abbreviation: 'MART').
	(self offset: 300 minutes name: 'Mawson Time' abbreviation: 'MAWT').
	(self offset: -360 minutes name: 'Mountain Daylight Time' abbreviation: 'MDT').
	(self offset: 720 minutes name: 'Marshall Islands Time' abbreviation: 'MHT').
	(self offset: 390 minutes name: 'Myanmar Time' abbreviation: 'MMT').
	(self offset: 240 minutes name: 'Moscow Daylight Time' abbreviation: 'MSD').
	(self offset: 180 minutes name: 'Moscow Standard Time' abbreviation: 'MSK').
	(self offset: -420 minutes name: 'Mountain Standard Time' abbreviation: 'MST').
	(self offset: 240 minutes name: 'Mauritius Time' abbreviation: 'MUT').
	(self offset: 300 minutes name: 'Maldives Time' abbreviation: 'MVT').
	(self offset: 480 minutes name: 'Malaysia Time' abbreviation: 'MYT').
	(self offset: -60 minutes name: 'November Time Zone' abbreviation: 'N').
	(self offset: 660 minutes name: 'New Caledonia Time' abbreviation: 'NCT').
	(self offset: -150 minutes name: 'Newfoundland Daylight Time' abbreviation: 'NDT').
	(self offset: 690 minutes name: 'Norfolk Time' abbreviation: 'NFT').
	(self offset: 420 minutes name: 'Novosibirsk Summer Time' abbreviation: 'NOVST').
	(self offset: 360 minutes name: 'Novosibirsk Time' abbreviation: 'NOVT').
	(self offset: 345 minutes name: 'Nepal Time' abbreviation: 'NPT').
	(self offset: -210 minutes name: 'Newfoundland Standard Time' abbreviation: 'NST').
	(self offset: -660 minutes name: 'Niue Time' abbreviation: 'NUT').
	(self offset: 780 minutes name: 'New Zealand Daylight Time' abbreviation: 'NZDT').
	(self offset: 780 minutes name: 'New Zealand Daylight Time' abbreviation: 'NZDT').
	(self offset: 720 minutes name: 'New Zealand Standard Time' abbreviation: 'NZST').
	(self offset: 720 minutes name: 'New Zealand Standard Time' abbreviation: 'NZST').
	(self offset: -120 minutes name: 'Oscar Time Zone' abbreviation: 'O').
	(self offset: 420 minutes name: 'Omsk Summer Time' abbreviation: 'OMSST').
	(self offset: 360 minutes name: 'Omsk Standard Time' abbreviation: 'OMST').
	(self offset: -180 minutes name: 'Papa Time Zone' abbreviation: 'P').
	(self offset: -420 minutes name: 'Pacific Daylight Time' abbreviation: 'PDT').
	(self offset: -300 minutes name: 'Peru Time' abbreviation: 'PET').
	(self offset: 720 minutes name: 'Kamchatka Summer Time' abbreviation: 'PETST').
	(self offset: 720 minutes name: 'Kamchatka Time' abbreviation: 'PETT').
	(self offset: 600 minutes name: 'Papua New Guinea Time' abbreviation: 'PGT').
	(self offset: 780 minutes name: 'Phoenix Island Time' abbreviation: 'PHOT').
	(self offset: 480 minutes name: 'Philippine Time' abbreviation: 'PHT').
	(self offset: 300 minutes name: 'Pakistan Standard Time' abbreviation: 'PKT').
	(self offset: -120 minutes name: 'Pierre & Miquelon Daylight Time' abbreviation: 'PMDT').
	(self offset: -180 minutes name: 'Pierre & Miquelon Standard Time' abbreviation: 'PMST').
	(self offset: 660 minutes name: 'Pohnpei Standard Time' abbreviation: 'PONT').
	(self offset: -480 minutes name: 'Pacific Standard Time' abbreviation: 'PST').
	(self offset: -480 minutes name: 'Pitcairn Standard Time' abbreviation: 'PST').
	(self offset: -480 minutes name: 'Tiempo del Pacífico' abbreviation: 'PT').
	(self offset: 540 minutes name: 'Palau Time' abbreviation: 'PWT').
	(self offset: -180 minutes name: 'Paraguay Summer Time' abbreviation: 'PYST').
	(self offset: -240 minutes name: 'Paraguay Time' abbreviation: 'PYT').
	(self offset: -240 minutes name: 'Quebec Time Zone' abbreviation: 'Q').
	(self offset: -300 minutes name: 'Romeo Time Zone' abbreviation: 'R').
	(self offset: 240 minutes name: 'Reunion Time' abbreviation: 'RET').
	(self offset: -360 minutes name: 'Sierra Time Zone' abbreviation: 'S').
	(self offset: 240 minutes name: 'Samara Time' abbreviation: 'SAMT').
	(self offset: 120 minutes name: 'South Africa Standard Time' abbreviation: 'SAST').
	(self offset: 660 minutes name: 'Solomon IslandsTime' abbreviation: 'SBT').
	(self offset: 240 minutes name: 'Seychelles Time' abbreviation: 'SCT').
	(self offset: 480 minutes name: 'Singapore Time' abbreviation: 'SGT').
	(self offset: -180 minutes name: 'Suriname Time' abbreviation: 'SRT').
	(self offset: -660 minutes name: 'Samoa Standard Time' abbreviation: 'SST').
	(self offset: -420 minutes name: 'Tango Time Zone' abbreviation: 'T').
	(self offset: -600 minutes name: 'Tahiti Time' abbreviation: 'TAHT').
	(self offset: 300 minutes name: 'French Southern and Antarctic Time' abbreviation: 'TFT').
	(self offset: 300 minutes name: 'Tajikistan Time' abbreviation: 'TJT').
	(self offset: -600 minutes name: 'Tokelau Time' abbreviation: 'TKT').
	(self offset: 540 minutes name: 'East Timor Time' abbreviation: 'TLT').
	(self offset: 300 minutes name: 'Turkmenistan Time' abbreviation: 'TMT').
	(self offset: 720 minutes name: 'Tuvalu Time' abbreviation: 'TVT')}