*jqwidgetbox-fullcalendar-core
timeZonesAtoG
	^ {(self offset: -180 minutes name: 'Atlantic Daylight Time' abbreviation: 'ADT').
	(self offset: -180 minutes name: 'Atlantic Daylight Time' abbreviation: 'ADT').
	(self offset: 270 minutes name: 'Afghanistan Time' abbreviation: 'AFT').
	(self offset: -480 minutes name: 'Alaska Daylight Time' abbreviation: 'AKDT').
	(self offset: -540 minutes name: 'Alaska Standard Time' abbreviation: 'AKST').
	(self offset: 360 minutes name: 'Alma-Ata Time' abbreviation: 'ALMT').
	(self offset: 300 minutes name: 'Armenia Summer Time' abbreviation: 'AMST').
	(self offset: -180 minutes name: 'Amazon Summer Time' abbreviation: 'AMST').
	(self offset: 240 minutes name: 'Armenia Time' abbreviation: 'AMT').
	(self offset: -240 minutes name: 'Amazon Time' abbreviation: 'AMT').
	(self offset: 720 minutes name: 'Anadyr Summer Time' abbreviation: 'ANAST').
	(self offset: 720 minutes name: 'Anadyr Time' abbreviation: 'ANAT').
	(self offset: 300 minutes name: 'Aqtobe Time' abbreviation: 'AQTT').
	(self offset: -180 minutes name: 'Argentina Time' abbreviation: 'ART').
	(self offset: 180 minutes name: 'Arabia Standard Time' abbreviation: 'AST').
	(self offset: -240 minutes name: 'Atlantic Standard Time' abbreviation: 'AST').
	(self offset: -240 minutes name: 'Atlantic Standard Time' abbreviation: 'AST').
	(self offset: -240 minutes name: 'Atlantic Standard Time' abbreviation: 'AST').
	(self offset: 0 minutes name: 'Azores Summer Time' abbreviation: 'AZOST').
	(self offset: -60 minutes name: 'Azores Time' abbreviation: 'AZOT').
	(self offset: 300 minutes name: 'Azerbaijan Summer Time' abbreviation: 'AZST').
	(self offset: 240 minutes name: 'Azerbaijan Time' abbreviation: 'AZT').
	(self offset: 120 minutes name: 'Bravo Time Zone' abbreviation: 'B').
	(self offset: 480 minutes name: 'Brunei Darussalam Time' abbreviation: 'BNT').
	(self offset: -240 minutes name: 'Bolivia Time' abbreviation: 'BOT').
	(self offset: -120 minutes name: 'Brasilia Summer Time' abbreviation: 'BRST').
	(self offset: -180 minutes name: 'Brasília time' abbreviation: 'BRT').
	(self offset: 360 minutes name: 'Bangladesh Standard Time' abbreviation: 'BST').
	(self offset: 360 minutes name: 'Bhutan Time' abbreviation: 'BTT').
	(self offset: 180 minutes name: 'Charlie Time Zone' abbreviation: 'C').
	(self offset: 480 minutes name: 'Casey Time' abbreviation: 'CAST').
	(self offset: 120 minutes name: 'Central Africa Time' abbreviation: 'CAT').
	(self offset: 390 minutes name: 'Cocos Islands Time' abbreviation: 'CCT').
	(self offset: 630 minutes name: 'Central Daylight Time' abbreviation: 'CDT').
	(self offset: -240 minutes name: 'Cuba Daylight Time' abbreviation: 'CDT').
	(self offset: -300 minutes name: 'Central Daylight Time' abbreviation: 'CDT').
	(self offset: 120 minutes name: 'Central European Summer Time' abbreviation: 'CEST').
	(self offset: 60 minutes name: 'Central European Time' abbreviation: 'CET').
	(self offset: 60 minutes name: 'Central European Time' abbreviation: 'CET').
	(self offset: 825 minutes name: 'Chatham Island Daylight Time' abbreviation: 'CHADT').
	(self offset: 765 minutes name: 'Chatham Island Standard Time' abbreviation: 'CHAST').
	(self offset: -600 minutes name: 'Cook Island Time' abbreviation: 'CKT').
	(self offset: -180 minutes name: 'Chile Summer Time' abbreviation: 'CLST').
	(self offset: -240 minutes name: 'Chile Standard Time' abbreviation: 'CLT').
	(self offset: -300 minutes name: 'Colombia Time' abbreviation: 'COT').
	(self offset: 480 minutes name: 'China Standard Time' abbreviation: 'CST').
	(self offset: 570 minutes name: 'Central Standard Time' abbreviation: 'CST').
	(self offset: -360 minutes name: 'Central Standard Time' abbreviation: 'CST').
	(self offset: -300 minutes name: 'Cuba Standard Time' abbreviation: 'CST').
	(self offset: -360 minutes name: 'Central Standard Time' abbreviation: 'CST').
	(self offset: -60 minutes name: 'Cape Verde Time' abbreviation: 'CVT').
	(self offset: 420 minutes name: 'Christmas Island Time' abbreviation: 'CXT').
	(self offset: 600 minutes name: 'Chamorro Standard Time' abbreviation: 'ChST').
	(self offset: 240 minutes name: 'Delta Time Zone' abbreviation: 'D').
	(self offset: 420 minutes name: 'Davis Time' abbreviation: 'DAVT').
	(self offset: 300 minutes name: 'Echo Time Zone' abbreviation: 'E').
	(self offset: -300 minutes name: 'Easter Island Summer Time' abbreviation: 'EASST').
	(self offset: -360 minutes name: 'Easter Island Standard Time' abbreviation: 'EAST').
	(self offset: 180 minutes name: 'Eastern Africa Time' abbreviation: 'EAT').
	(self offset: 180 minutes name: 'East Africa Time' abbreviation: 'EAT').
	(self offset: -300 minutes name: 'Ecuador Time' abbreviation: 'ECT').
	(self offset: 660 minutes name: 'Eastern Daylight Time' abbreviation: 'EDT').
	(self offset: -240 minutes name: 'Eastern Daylight Time' abbreviation: 'EDT').
	(self offset: -240 minutes name: 'Eastern Daylight Time' abbreviation: 'EDT').
	(self offset: 660 minutes name: 'Eastern Daylight Time' abbreviation: 'EDT').
	(self offset: 180 minutes name: 'Eastern European Summer Time' abbreviation: 'EEST').
	(self offset: 180 minutes name: 'Eastern European Summer Time' abbreviation: 'EEST').
	(self offset: 180 minutes name: 'Eastern European Summer Time' abbreviation: 'EEST').
	(self offset: 120 minutes name: 'Eastern European Time' abbreviation: 'EET').
	(self offset: 120 minutes name: 'Eastern European Time' abbreviation: 'EET').
	(self offset: 120 minutes name: 'Eastern European Time' abbreviation: 'EET').
	(self offset: 0 minutes name: 'Eastern Greenland Summer Time' abbreviation: 'EGST').
	(self offset: -60 minutes name: 'East Greenland Time' abbreviation: 'EGT').
	(self offset: 600 minutes name: 'Eastern Standard Time' abbreviation: 'EST').
	(self offset: -300 minutes name: 'Eastern Standard Time' abbreviation: 'EST').
	(self offset: -300 minutes name: 'Eastern Standard Time' abbreviation: 'EST').
	(self offset: -300 minutes name: 'Eastern Standard Time' abbreviation: 'EST').
	(self offset: -300 minutes name: 'Tiempo del Este' abbreviation: 'ET').
	(self offset: -300 minutes name: 'Tiempo del Este' abbreviation: 'ET').
	(self offset: -300 minutes name: 'Tiempo Del Este' abbreviation: 'ET').
	(self offset: 360 minutes name: 'Foxtrot Time Zone' abbreviation: 'F').
	(self offset: 780 minutes name: 'Fiji Summer Time' abbreviation: 'FJST').
	(self offset: 720 minutes name: 'Fiji Time' abbreviation: 'FJT').
	(self offset: -180 minutes name: 'Falkland Islands Summer Time' abbreviation: 'FKST').
	(self offset: -240 minutes name: 'Falkland Island Time' abbreviation: 'FKT').
	(self offset: -120 minutes name: 'Fernando de Noronha Time' abbreviation: 'FNT').
	(self offset: 420 minutes name: 'Golf Time Zone' abbreviation: 'G').
	(self offset: -360 minutes name: 'Galapagos Time' abbreviation: 'GALT').
	(self offset: -540 minutes name: 'Gambier Time' abbreviation: 'GAMT').
	(self offset: 240 minutes name: 'Georgia Standard Time' abbreviation: 'GET').
	(self offset: -180 minutes name: 'French Guiana Time' abbreviation: 'GFT').
	(self offset: 720 minutes name: 'Gilbert Island Time' abbreviation: 'GILT').
	(self offset: 0 minutes name: 'Greenwich Mean Time' abbreviation: 'GMT').
	(self offset: 0 minutes name: 'Greenwich Mean Time' abbreviation: 'GMT').
	(self offset: 240 minutes name: 'Gulf Standard Time' abbreviation: 'GST').
	(self offset: -240 minutes name: 'Guyana Time' abbreviation: 'GYT')}