*jqwidgetbox-fullcalendar-core
timeZonesUtoZ
	^ {(self offset: -480 minutes name: 'Uniform Time Zone' abbreviation: 'U').
	(self offset: 480 minutes name: 'Ulaanbaatar Time' abbreviation: 'ULAT').
	(self offset: -120 minutes name: 'Uruguay Summer Time' abbreviation: 'UYST').
	(self offset: -180 minutes name: 'Uruguay Time' abbreviation: 'UYT').
	(self offset: 300 minutes name: 'Uzbekistan Time' abbreviation: 'UZT').
	(self offset: -540 minutes name: 'Victor Time Zone' abbreviation: 'V').
	(self offset: -270 minutes name: 'Venezuelan Standard Time' abbreviation: 'VET').
	(self offset: 660 minutes name: 'Vladivostok Summer Time' abbreviation: 'VLAST').
	(self offset: 600 minutes name: 'Vladivostok Time' abbreviation: 'VLAT').
	(self offset: 660 minutes name: 'Vanuatu Time' abbreviation: 'VUT').
	(self offset: -600 minutes name: 'Whiskey Time Zone' abbreviation: 'W').
	(self offset: 120 minutes name: 'West Africa Summer Time' abbreviation: 'WAST').
	(self offset: 60 minutes name: 'West Africa Time' abbreviation: 'WAT').
	(self offset: 540 minutes name: 'Western Daylight Time' abbreviation: 'WDT').
	(self offset: 60 minutes name: 'Western European Summer Time' abbreviation: 'WEST').
	(self offset: 60 minutes name: 'Western European Summer Time' abbreviation: 'WEST').
	(self offset: 0 minutes name: 'Western European Time' abbreviation: 'WET').
	(self offset: 0 minutes name: 'Western European Time' abbreviation: 'WET').
	(self offset: 720 minutes name: 'Wallis and Futuna Time' abbreviation: 'WFT').
	(self offset: -120 minutes name: 'Western Greenland Summer Time' abbreviation: 'WGST').
	(self offset: -180 minutes name: 'West Greenland Time' abbreviation: 'WGT').
	(self offset: 420 minutes name: 'Western Indonesian Time' abbreviation: 'WIB').
	(self offset: 540 minutes name: 'Eastern Indonesian Time' abbreviation: 'WIT').
	(self offset: 480 minutes name: 'Central Indonesian Time' abbreviation: 'WITA').
	(self offset: 60 minutes name: 'Western Sahara Summer Time' abbreviation: 'WST').
	(self offset: 480 minutes name: 'Western Standard Time' abbreviation: 'WST').
	(self offset: -660 minutes name: 'West Samoa Time' abbreviation: 'WST').
	(self offset: 0 minutes name: 'Western Sahara Standard Time' abbreviation: 'WT').
	(self offset: -660 minutes name: 'X-ray Time Zone' abbreviation: 'X').
	(self offset: -720 minutes name: 'Yankee Time Zone' abbreviation: 'Y').
	(self offset: 600 minutes name: 'Yakutsk Summer Time' abbreviation: 'YAKST').
	(self offset: 540 minutes name: 'Yakutsk Time' abbreviation: 'YAKT').
	(self offset: 600 minutes name: 'Yap Time' abbreviation: 'YAPT').
	(self offset: 360 minutes name: 'Yekaterinburg Summer Time' abbreviation: 'YEKST').
	(self offset: 300 minutes name: 'Yekaterinburg Time' abbreviation: 'YEKT').
	(self offset: 0 minutes name: 'Zulu Time Zone' abbreviation: 'Z')}