updating
style
	^'
	#box1, #box2, #box3 {
	float: left;
	margin: 0 0 30px 50px;
	width: 100px;
	height: 50px;
	border-radius: 10px;
	-moz-border-radius: 10px;
	-webkit-border-radius: 10px;
	line-height: 45px;
	text-align: center;
	border: 3px solid #a9a9a9;
}

#box1 {
	box-shadow: 0 0 10px #000000;
	-moz-box-shadow: 0 0 10px #000000;
	-webkit-box-shadow: 0 0 10px #000000;
}

#box2 {
	box-shadow: inset 0 0 0 #f80;
	-moz-box-shadow: inset 0 0 0 #f80;
	-webkit-box-shadow: inset 0 0 0 #f80;
}

#box3 {
	position: relative;
	box-shadow: 8px 8px 15px #666;
	-moz-box-shadow: 8px 8px 15px #666;
	-webkit-box-shadow: 8px 8px 15px #666;
}

h2 {
	clear: both;
}
	
	
	'