updating
style
	"This style is only for this example, not for to use the widgets."

	^'
html {
	height: 100%;
	overflow: hidden } 

body {
	overflow: hidden;
	height: 100%;
	margin: 0;
	padding: 0; }	

#left {
	overflow: auto;
	float: left;
	height: 100%;
	width: 270px;	
#	border: 1px solid #BBB;
}

#center {
	overflow: auto;
	float: left; 
	height: 100%;
#	border: 1px solid #BBB; 
}

#right { 
	overflow: auto;
	float: right;
	height: 100%;
	width: 322px;
#	border: 1px solid #BBB;
} 

 '