baselines
baselineWidgetCoreLibraries: spec
	spec
		package: 'JQWidgetBox-AccessibleNewsSlider-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-AlphaNumeric-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-Autocomplete-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-BubbleTip-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-Calculator-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-CheckTree-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-Cycle-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-DropShadow-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-Dynatree-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-EpiClock-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-FancyBox-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-Farbtastic-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-Fisheye-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-FontEffect-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-FormExample-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-FullCalendar-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-Growl-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-HoverIntent-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-ImageDropDown-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-InnerFade-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-JEditable-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-JQGrid-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-JQTools-Tabs-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-MapQuery-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-MbMenu-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-PageFold-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-Reflection-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-RegisteredInterval-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-SelectMenu-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-ShadowAnimation-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-Sheet-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-Spinner-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-Splitter-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-Stars-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-Tablesorter-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-Timepickr-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-TimeSlider-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-UILayout-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ];
		package: 'JQWidgetBox-WeekCalendar-Core'
			with: [ spec requires: 'JQWidgetBox-Core' ]