baselines
baselineWidgetDevelopmentExamples: spec
	spec
		package: 'JQWidgetBox-AccessibleNewsSlider-Dev'
			with: [ spec
				requires: #('JQWidgetBox-Dev' 'JQWidgetBox-AccessibleNewsSlider-Core') ];
		package: 'JQWidgetBox-AlphaNumeric-Dev'
			with:
				[ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-AlphaNumeric-Core') ];
		package: 'JQWidgetBox-Autocomplete-Dev'
			with:
				[ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-Autocomplete-Core') ];
		package: 'JQWidgetBox-BubbleTip-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-BubbleTip-Core') ];
		package: 'JQWidgetBox-Calculator-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-Calculator-Core') ];
		package: 'JQWidgetBox-CheckTree-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-CheckTree-Core') ];
		package: 'JQWidgetBox-Cycle-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-Cycle-Core') ];
		package: 'JQWidgetBox-DropShadow-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-DropShadow-Core') ];
		package: 'JQWidgetBox-Dynatree-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-Dynatree-Core') ];
		package: 'JQWidgetBox-EpiClock-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-EpiClock-Core') ];
		package: 'JQWidgetBox-FancyBox-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-FancyBox-Core') ];
		package: 'JQWidgetBox-Farbtastic-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-Farbtastic-Core') ];
		package: 'JQWidgetBox-Fisheye-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-Fisheye-Core') ];
		package: 'JQWidgetBox-FontEffect-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-FontEffect-Core') ];
		package: 'JQWidgetBox-FormExample-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-FormExample-Core') ];
		package: 'JQWidgetBox-FullCalendar-Dev'
			with:
				[ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-FullCalendar-Core') ];
		package: 'JQWidgetBox-Growl-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-Growl-Core') ];
		package: 'JQWidgetBox-HoverIntent-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-HoverIntent-Core') ];
		package: 'JQWidgetBox-ImageDropDown-Dev'
			with:
				[ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-ImageDropDown-Core') ];
		package: 'JQWidgetBox-InnerFade-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-InnerFade-Core') ];
		package: 'JQWidgetBox-JEditable-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-JEditable-Core') ];
		package: 'JQWidgetBox-JQGrid-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-JQGrid-Core') ];
		package: 'JQWidgetBox-JQTools-Tabs-Dev'
			with:
				[ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-JQTools-Tabs-Core') ];
		package: 'JQWidgetBox-MapQuery-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-MapQuery-Core' )];
		package: 'JQWidgetBox-MbMenu-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-MbMenu-Core' )];
		package: 'JQWidgetBox-PageFold-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-PageFold-Core') ];
		package: 'JQWidgetBox-Reflection-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-Reflection-Core') ];
		package: 'JQWidgetBox-RegisteredInterval-Example'
			with: [ spec
				requires: #('JQWidgetBox-Dev' 'JQWidgetBox-RegisteredInterval-Core') ];
		package: 'JQWidgetBox-ShadowAnimation-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-ShadowAnimation-Core')];
		package: 'JQWidgetBox-Sheet-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-Sheet-Core') ];
		package: 'JQWidgetBox-Spinner-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-Spinner-Core') ];
		package: 'JQWidgetBox-Splitter-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-Splitter-Core') ];
		package: 'JQWidgetBox-Stars-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-Stars-Core') ];
		package: 'JQWidgetBox-Tablesorter-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-Tablesorter-Core') ];
		package: 'JQWidgetBox-Timepickr-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-Timepickr-Core')];
		package: 'JQWidgetBox-TimeSlider-Dev'
			with: [ spec requires: #('JQWidgetBox-TimeSlider-Core' 'JQWidgetBox-Dev') ];
		package: 'JQWidgetBox-UILayout-Dev'
			with: [ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-UILayout-Core')];
		package: 'JQWidgetBox-WeekCalendar-Dev'
			with:
				[ spec requires: #('JQWidgetBox-Dev' 'JQWidgetBox-WeekCalendar-Core') ]