rendering
renderNewsOn2: html

	html html: '<p class="skip_to_news"><a href="#skip_to_news">Skip to News</a></p>
	<p class="back"><a href="#" title="Back">&laquo; back</a></p>
	<p class="next"><a href="#" title="Next">next &raquo;</a></p>
	<a name="skip_to_news"></a>
	<ul>
		<li>
			<a href="/"><img src="photo.jpg" width="75" height="75" alt="Business Photo" /></a>
			<p>
				<a href="/">Sed imperdiet faucibus dui. Etiam malesuada.</a><br />
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sit amet felis.
			</p>
		</li>
		<li>
			<a href="/"><img src="photo.jpg" width="75" height="75" alt="Business Photo" /></a>
			<p>
				<a href="/">Sed imperdiet faucibus dui. Etiam malesuada.</a><br />
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sit amet felis.
			</p>
		</li>
		<li>
			<a href="/"><img src="photo.jpg" width="75" height="75" alt="Business Photo" /></a>
			<p>
				<a href="/">Sed imperdiet faucibus dui. Etiam malesuada.</a><br />
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sit amet felis.
			</p>
		</li>
		<li>
			<a href="/"><img src="photo.jpg" width="75" height="75" alt="Business Photo" /></a>
			<p>
				<a href="/">Sed imperdiet faucibus dui. Etiam malesuada.</a><br />
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sit amet felis.
			</p>
		</li>
		<li>
			<a href="/"><img src="photo.jpg" width="75" height="75" alt="Business Photo" /></a>
			<p>
				<a href="/">Sed imperdiet faucibus dui. Etiam malesuada.</a><br />
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sit amet felis.
			</p>
		</li>
		<li>
			<a href="/"><img src="photo.jpg" width="75" height="75" alt="Business Photo" /></a>
			<p>
				<a href="/">Sed imperdiet faucibus dui. Etiam malesuada.</a><br />
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sit amet felis.
			</p>
		</li>
		<li>
			<a href="/"><img src="photo.jpg" width="75" height="75" alt="Business Photo" /></a>
			<p>
				<a href="/">Sed imperdiet faucibus dui. Etiam malesuada.</a><br />
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sit amet felis.
			</p>
		</li>
		<li>
			<a href="/"><img src="photo.jpg" width="75" height="75" alt="Business Photo" /></a>
			<p>
				<a href="/">Sed imperdiet faucibus dui. Etiam malesuada.</a><br />
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sit amet felis.
			</p>
		</li>
	</ul>'